/**
 * Generic hook factory for CRUD operations on any data type
 * Eliminates duplication across useNotes, useJournal, usePeople, usePlaces hooks
 * 
 * Usage:
 *   export const useNotes = createDataHook('notes', db.notes);
 *   export const useJournal = createDataHook('journal', db.journal);
 */
import { useLiveQuery } from 'dexie-react-hooks';
import { useAuth } from './useAuth';
import { syncManager } from '../lib/sync';
import { newId, now } from '../lib/helpers';
import type { BaseRecord } from '../type/BaseType';
import type { Table, UpdateSpec } from 'dexie';

type TableName = 'notes' | 'journal' | 'people' | 'places';

/**
 * Create a generic CRUD hook for a data table
 * @param table - Name of the table
 * @param dbTable - Dexie table reference
 * @returns Hook that provides CRUD operations
 */
export function createDataHook<T extends BaseRecord>(
  table: TableName,
  dbTable: Table<T, string>,
) {
  return function useDataHook() {
    const { user, synced } = useAuth();

    // Get all records for user (live query updates on changes)
    // Returns undefined until the first query resolves.
    // We use `synced` (from auth) as the primary loading gate so the skeleton
    // only shows while the initial API pull is in progress, not while Dexie
    // is doing its first async read (which causes a false undefined flash).
    const items = useLiveQuery(
      () => {
        if (!user?.id) return [];
        return dbTable.where('userId').equals(user.id).toArray();
      },
      [user?.id]
    );

    // isLoading is true only while the initial server sync hasn't completed
    // AND Dexie hasn't resolved its first query yet.
    // Once synced=true (set immediately from cache on refresh, or after
    // first pull on login), pages render from Dexie without any skeleton.
    const isLoading = !synced && items === undefined;

    /**
     * Create a new record.
     * If `data` contains an `id` field (pre-generated by the editor so images
     * can be uploaded before the record is saved), that ID is used as-is.
     * Otherwise a new UUID is generated here.
     */
    const create = async (data: Omit<T, 'id' | 'userId' | 'createdAt' | 'updatedAt'> & { id?: string }): Promise<T> => {
      if (!user?.id) throw new Error('User not authenticated');

      const record: T = {
        ...data,
        id: (data.id && data.id.trim().length) ? data.id : newId(),   // honour non-empty pre-generated ID from editor
        userId: user.id,
        createdAt: now(),
        updatedAt: now(),
      } as T;

      await dbTable.add(record);
      syncManager.queueOperation(user.id, table, 'create', record.id, record);
      return record;
    };

    /**
     * Update an existing record
     */
    const update = async (
      id: string,
      updates: Partial<Omit<T, 'id' | 'userId' | 'createdAt'>>
    ): Promise<void> => {
      if (!user?.id) throw new Error('User not authenticated');

      const updateData: UpdateSpec<T> = {
        ...updates,
        updatedAt: now(),
      } as UpdateSpec<T>;

      await dbTable.update(id, updateData);
      syncManager.queueOperation(user.id, table, 'update', id, updateData);
    };

    /**
     * Delete a record
     */
    const remove = async (id: string): Promise<void> => {
      if (!user?.id) throw new Error('User not authenticated');

      await dbTable.delete(id);
      syncManager.queueOperation(user.id, table, 'delete', id);
    };

    /**
     * Get a single record by id
     */
    const getById = async (id: string): Promise<T | undefined> => {
      if (!user?.id) return undefined;
      return dbTable.where('id').equals(id).and((record: T) => record.userId === user.id).first();
    };

    return {
      // undefined = not yet loaded (show skeleton), array = loaded (even if empty)
      items,
      isLoading,
      create,
      update,
      remove,
      getById,
    };
  };
}
